---

- name: Debug connect
  hosts: local
  become: yes
  
  tasks:
    - name: Debug 
      debug: 
       msg: hello ansible, {{ item }} 
      with_items:
       - Petya
       - Vasya
       - Mitya
    - name: "Install neofetch"
      apt: name=neofetch state=present
    - name: Start app
      shell: neofetch 
